rsync -av ./training_examples_full/Moorhouse*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Adelaide*ds75*examples ./training_examples_selected
rsync -av ./training_examples_full/Kotiu*ds85*examples ./training_examples_selected
rsync -av ./training_examples_full/Ruggedy*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Fuchsia*ds75*examples ./training_examples_selected
rsync -av ./training_examples_full/Marama*ds85*examples ./training_examples_selected
rsync -av ./training_examples_full/Oraka*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Tuterangi*ds75*examples ./training_examples_selected
rsync -av ./training_examples_full/Zephyr*ds85*examples ./training_examples_selected
rsync -av ./training_examples_full/Queenie*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Sarah*ds75*examples ./training_examples_selected
rsync -av ./training_examples_full/Taeatanga*ds85*examples ./training_examples_selected
rsync -av ./training_examples_full/Ralph*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Kuia*ds75*examples ./training_examples_selected
rsync -av ./training_examples_full/Merv*ds85*examples ./training_examples_selected
rsync -av ./training_examples_full/Lionel*ds0*examples ./training_examples_selected
rsync -av ./training_examples_full/Aumaria*ds0*examples ./validation_examples_selected
rsync -av ./training_examples_full/Awhero*ds75*examples ./validation_examples_selected
rsync -av ./training_examples_full/Guapo*ds85*examples ./validation_examples_selected
rsync -av ./training_examples_full/Rakiura*ds0*examples ./validation_examples_selected
rsync -av ./training_examples_full/Juanma*ds75*examples ./validation_examples_selected
rsync -av ./training_examples_full/Kuihi*ds85*examples ./validation_examples_selected
rsync -av ./training_examples_full/Sinbad*ds0*examples ./validation_examples_selected
rsync -av ./training_examples_full/Boss*ds75*examples ./validation_examples_selected
rsync -av ./training_examples_full/Felix*ds85*examples ./validation_examples_selected
